services:
  telegram-log-service:
    build:
      context: .
    container_name: telegram-log-service
    ports:
      - "8000:8000"
    volumes:
      - .:/app 
    networks:
      - constructionAutomation
  
networks:
  constructionAutomation:
    external: true